### ISSUE TITLE
Fix url variable

### ISSUE THREAD

**Issue by jeansg** [tibiamaps/tibia-maps-installer-linux#1]
The given URL is returning 404, need to adjust 

from:
`url='https://tibiamaps.io/downloads/automap-*-markers';`

To:
`url='https://tibiamaps.io/downloads/minimap-*-markers';`

**Comment by mathiasbynens** [comment]
Oh yeah, I forgot to update this script when the Tibia 11 client launched.

Where does the Linux client store its data? Is it still in `~/.tibia`?

**Comment by jeansg** [comment]
I've decompressed the .tar.gz in my home and created a symbolic link to the folder created so I've changed the script to decompress the maps in ~/tibia

$ ls  -l tibia 
lrwxrwxrwx 1 jeanguirro jeanguirro 17 mai  6 18:30 tibia -> tibia-11.74.6781/

$ find tibia/* -maxdepth 0 -type d
tibia/3rdpartylicences
tibia/assets
tibia/bin
tibia/cache
tibia/characterdata
tibia/conf
tibia/crashdump
tibia/log
tibia/**minimap**
tibia/storeimages

**Comment by mathiasbynens** [comment]
Are you saying the new client stores the files in whatever directory its executable is in? 🤔

**Comment by jeansg** [comment]
Yes, the .tar.gz they provide "http://download.tibia.com/tibia.x64.tar.gz" it's just that, so I can decompress wherever I want, in my notebook I was using a script to download and put in a "default" folder at my home

**Comment by Bernardoow** [comment]
@mathiasbynens 

Today was launched the Linux client. http://forum.tibia.com/forum/?action=thread&threadid=4661648

In my computer the local is /home/bernardo/.local/share/CipSoft\ GmbH/Tibia/packages/Tibia/minimap or 
~/.local/share/CipSoft\ GmbH/Tibia/packages/Tibia/
